---
title: "Let's see"
author: "Me"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
x <- 1:16
y <- 17:32

m <- matrix(nrow=2, ncol=16, byrow=TRUE)
q <- matrix(nrow=16, ncol=2, byrow=TRUE)

m2 <- rbind(x, y)
q2 <- cbind(x, y)

m2
q2

sequencial <- seq(1, 25)
new_seq <- as.matrix(sequencial)

colnames(q) <- c("business_index", "projection")

new_seq[[15]]
```

Lists

```{r}
lst <- list(a="1", b=4)

lst$a
```

Some random weirdo

```{r}
lst <- c(6, 5,33, 8, 19, 22, 8, 11)

as.factor(lst)
barplot(lst)
hist(lst)
```

Some weird sht

```{r}
gend <- c("male", "female", "female", "male", "male")
gender <- c(1,2,2,1,1,1)

pie(gender, labels=names(gender), edges=150, radius=0.8, angle=45)
```

Tabular Monkey

```{r}
emp.data <- data.frame(emp_id=c(1:5), emp_name=c("Rick","Dan","Michelle","Ryan","Gary"), salary=c(234,234,425,674,1292))

emp.data
```

Naming

```{r}
x <- c(5:8)

names(x) <- c("Five", "Six", "Seven", "Eight")

x
names(x)
```

Subsetting

```{r}
play <- c(1:5)

play[2]
play[2:4]
play[[3]]

joke <- list("Me", 4, TRUE)
#joke[2] # interesting...
joke[[2]]
```

Oloshi

```{r}
apple <- c("b", "d", "f", "g", "e")
xray <- c("a", "b", "c", "d", "e")

xray[apple > "g"]
```

Testing out subsetting with two different stuffs

```{r}
a <- c(2, 5, 6, 3, 5)
b <- c(1, 2, 3, 4, 5)

b[a <= 5] # it runs the inner condition inside the square brackets, then finally maps to the actual vector
```

Subsetting

```{r}
mtrx <- matrix(1:16, 4, 4)
mtrx[2, 3]

mtrx[1, , drop=FALSE]
```

Tasks

```{r}
dataset <- c(3.45, 2, 4, 6.5, 3, 4, 2.5, 1, 8, 7.5, 4.75, 5, 3, 2.25, 9, 7.75)
mtrx <- matrix(dataset, 4, 4)

colnames(mtrx) <- c("x-axis", "y-axis", "z-axis", "monkey-axis")

mtrx
mtrx[1, 2]

cheat <- mtrx[1:3, 3:4]
```
